import Head from "next/head";
import { Inter } from "@next/font/google";
import About from "@/components/templates/About";
import Targets from "@/components/templates/Targets";
import News from "@/components/templates/News";
import Partners from "@/components/templates/Partners";
import Faculties from "@/components/templates/Faculties";
import faculty1 from "../assets/faculty.svg";
import faculty2 from "../assets/faculty2.svg";
import Maps from "@/components/templates/Maps";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  console.log(process.env.NEXT_PUBLIC_GOOGLE_MAPS_KEY);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <About />
        <Targets />
        <News />
        <Partners />
        <Faculties faculty="Bakalavr" image={faculty1} bg="bg-white" />
        <Faculties faculty="Magistr" image={faculty2} bg="bg-secondary-50" />
        <Maps />
      </main>
    </>
  );
}
